"""
Vague Answer Detector
Detects when users give vague/generic answers and generates quirky follow-ups
"""

import logging
import random
from typing import Optional

logger = logging.getLogger(__name__)


class VagueAnswerDetector:
    """
    Detects vague answers and generates context-aware follow-ups
    Maintains "Well-Connected Insider" persona
    """

    def __init__(self, response_engine=None):
        self.response_engine = response_engine
        
    def is_vague(self, answer: str, context: str = 'default', question: str = "") -> bool:
        """
        Check if an answer is too vague using LLM
        """
        if not self.response_engine:
            logger.warning("ResponseEngine not provided to VagueAnswerDetector")
            return False
            
        result = self.response_engine.check_vagueness(question, answer)
        
        # Store the follow-up for later retrieval
        self.last_follow_up = result.get('follow_up')
        
        is_vague = result.get('is_vague', False)
        if is_vague:
            logger.info(f"LLM detected vague answer: {answer} (Reason: {result.get('reason')})")
            
        return is_vague

    def generate_follow_up(self, vague_answer: str, context: str = 'default',
                          original_question: str = "") -> str:
        """
        Get the follow-up generated by the LLM
        """
        if hasattr(self, 'last_follow_up') and self.last_follow_up:
            return self.last_follow_up
            
        return "Can you be more specific?"

    def get_context_from_question(self, question: str) -> str:
        """
        Determine context from the question - kept for logging purposes
        """
        return "general"


if __name__ == "__main__":
    # Test vague answer detector
    detector = VagueAnswerDetector()

    test_cases = [
        ("What are you working towards?", "stuff", "goals"),
        ("How long have you been coding?", "a while", "trajectory"),
        ("What challenges have you solved?", "idk", "problems"),
        ("What are your goals?", "grow", "goals"),
        ("What are you focused on?", "I'm trying to scale my startup to 1M users", "goals"),
    ]

    print("=== Vague Answer Detector Test ===\n")

    for question, answer, expected_context in test_cases:
        print(f"Q: {question}")
        print(f"A: {answer}")
        
        context = detector.get_context_from_question(question)
        is_vague = detector.is_vague(answer, context)
        
        print(f"Context: {context}")
        print(f"Is vague: {is_vague}")
        
        if is_vague:
            follow_up = detector.generate_follow_up(answer, context, question)
            print(f"Follow-up: {follow_up}")
        
        print()
